apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-cp4i-apic
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/cp4i-apic/namespace
    repoURL: https://github.com/vijayksorg/gitops-test-cp4i-all-5-1
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
