apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: cp4i-apic
spec:
  encryptedData:
    .dockerconfigjson: AgBU4KhxE6VOJMmygKyByrreR6f0zzinimMSVdCg8wR9eWes8Pvutw1gdIkpemFDAVkkgOQW3bplY8UVPT5ZH28t6woaqbooi6wk2GGEbYwxQrox7ji8fr90Bv1fmLfc/WlSw85bo+/AOFJQLoojFcP3mQVQ0IPPEAmlQaIrpAcXUa+YfBlPfGcgP1zZdANXqVUvESnP0v/EHejZut7BFNFAG+QsJ5+3KjECHsi1c7NxMaiQ9Ij/44o+6NwSi82JsY7vQzN1mQgSfwCgZIZlsvbLQ438BV08BgIJYAUyraxiWYjmh1PYqO2CITXaZBC8UJ2rb+FPw0YN4od4t//5EkIt+pnwEGPCASTT0b9TSzArTRORqDRbIE51+jEF1g/kNltGXiyjqLdaqNWKjehVPAQgpskftdnSZgR5Ft/YWrk0m8fYcGJQpUO3hA/u7WT0pldy98X+VxQ32Ie7vIvGcjYxwS0AvBybaF+36cn/ox8IOZvNxiKp94A3vJQ43rOMt8939hFuVMTEi5Vi9GTSRNgKUDFEqVFRU5DD2rUqi45eCgMmIHBPlONazPHtiNWlYzunpYDZr+VMMCFDUCyCdc65jOqFxZMSrXyHDxn6wnZNs+gyyJhphlGEvuE9IYZ0QcZBrZ8vm+03ZAaHDdL0lDVIQDiNHY1hjgAbwEK3iZceDtLcLkRrEN0n39+Aqlt6Cz6ZJqN9zUmgVwqpeciLtwkg+Uzv5Ps+NOPaY2jsADhSgDsxEfR90Cpe6LeFNSo5BD9ZIQ54PzsPN6Ap9J1rLnUnWQIOfdWBTbmYRpKN5NHG1azvQZOZrvQvVAnO76GvtNgSHVX3ha9oapl7SFOLPs2teZuqACfEO88Xs0vYEAMTRf8RRQYB5RebiyCuGuiHeeKy+qz4yxbuVA1DrT6Ovb4/JtcYBLxhISzfvdpvg/eHs138Vi5+U32dPRW+fZEe3s5UfnOa6OS+40pQis4sPnw3tOrKgbXL1SjZo81deD6GKnv+apuvdwGAJKdLxpJgGsiirZdRpEJ7cBeHbq/lsaRqWBrGEpDWt5c90bXgx8uKLOttdr8+/A106+w6jRafs/vl5nw84bkruEF+RF9KJvrNrbbhNdeRPPhVLGDmoBhFgnaqqzl9k2fEnqUsgWIewjMl3zzh4HMCyDad9uubcunKcOdGz+hvv2JqY4cp//SFw1RhFoAsuu74ei5MTtHRjKqhFuBUZKtn2HynrXjayP+r+lVsg2kWJgZeirgPUU9o0DvPIGz+8DMsF6S54UEZz3HSbemKX3AGiGQG8ji4zKW/r6opgN+9+EC0s39Yymz7FE9uZnfn0Kk6w3b0H9XgWqvC
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: cp4i-apic
    type: kubernetes.io/dockerconfigjson

